name: Build and deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Test & build Winter
        run: |
          go test ./...
          go build -ldflags="-X 'main.version=${{ env.GITHUB_REF }}'" -o w .
